### ISSUE TITLE
Is it possible to integrate it into a forward renderer?

### ISSUE THREAD

**Issue by ohmaya** [NVIDIAGameWorks/KickstartRT#17]
Thanks.

**Comment by bryandudashnv** [comment]
Hello @ohmaya , thanks for the question.  Kickstart RT requires various gbuffer inputs (depth, normals, roughness, specular and color buffers).  Additionally, it provides output buffers which need to be integrated back into the scene lighting.  This will be problematic for a forward renderer where you do not have these inputs generally and would have difficulty to integrate the results back onto your final lit scene.
